<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@  page import="java.io.*"%>
<%@  page import="java.util.ArrayList"%>
<%@  page import="java.util.List"%>
<html>
<head>
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>

<!-- Required meta tags always come first -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="x-ua-compatible" content="ie=edge">

<!-- Bootstrap CSS -->
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.0/css/bootstrap.min.css">
<link rel="stylesheet" href="css/custom.css">

<!-- Fonts -->
<link
	href='https://fonts.googleapis.com/css?family=Lato:400,700,900,300'
	rel='stylesheet' type='text/css'>
<link
	href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic'
	rel='stylesheet' type='text/css'>
<link
	href='https://fonts.googleapis.com/css?family=Raleway:400,300,600,700,900'
	rel='stylesheet' type='text/css'>
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<title>Files including upload and file generating</title>
</head>
<body>
		<div class="container">
		<br> 
		<div class="">
			<h2 align="center">
				PepBCL<span class="pull-right label label-default"></span>
			</h2>
			<p align="center">A generic webserver for predicting m7G sites and extracting m7G feature representation.</p>
		</div>
		
			<div align="center">
						   <!-- 遍历Map集合 -->
						    <c:forEach var="me" items="${fileNameMap}">
						        <c:url value="/M6AMRFS/DownLoadServlet" var="downurl">
						            <c:param name="filename" value="${me.key}"></c:param>
						        </c:url>
						        <c:if test="${fn:contains(me.value,'.fasta') && fn:contains(me.value,'.fasta.')==false}">
						        	<div Style="left:0px;top:0px">${me.value} :<a href="${downurl}">download</a> &nbsp;&nbsp; (input file of fasta type) <br>
						        </c:if>
						        <c:if test="${fn:contains(me.value,'.fasta.csv')}">
						        	<div Style="left:0px;top:0px">${me.value} :<a href="${downurl}">download</a>&nbsp;&nbsp; (features generated by feature representation proposed in this study)<br>
						        </c:if>
						        <c:if test="${fn:contains(me.value,'.fasta.predict.csv')}">
						        	<div Style="left:0px;top:0px">${me.value} :<a href="${downurl}">download</a> &nbsp;&nbsp; (prediction files generated by prediction model) <br>
						        </c:if>
						        <c:if test="${fn:contains(me.value,'.fasta.bestfeaturesubset.csv')}">
						        	<div Style="left:0px;top:0px">${me.value} :<a href="${downurl}">download</a> &nbsp;&nbsp; (features after selecting based on corresponding feature selection algorithm) <br>
						        </c:if>
						        
						        
						       
						        <br/>
						    </c:forEach>
			
			</div>
			
			

									<div class="col-lg-11">
										<%
					List<String> showlist1 = (List<String>) request.getAttribute("prelist");
				%>


										<strong><h3 align="center">Results</h3></strong>

										<table class="table table-hover" border="1" align="center">
											<tr class="info">
												<td align="center">Title</td>
												<td align="center">Sequence</td>
												<td align="center">m4c-siteOrNot</td>
												<td align="center">Score</td>

											</tr>

											<%
						for (int i = 0; i < showlist1.size(); i++) {
								String[] show = showlist1.get(i).split(",");
								String yon="";
								if (show[2].equals("1")){ yon="m7G-site";}else{ yon="non-m7G-site";}
					%>
											<tr class="info">
												<td align="center"><%=show[0]%></td>
												<td align="center"><%=show[1]%></td>
												<td align="center"><%=yon%></td>
												<td align="center"><%=show[3]%></td>
											</tr>
											<%
						}
					%>
										</table>


										<br />

										


									</div>
									</div>

									<!-- <dic align="center">
    
    									<button id="btn_back" type="button"  class="btn btn-warning btn-center" style="width: 200px;" onclick="history.go(-1)">
    											Back
										</button>
    
    								</dic> -->
	<!-- JavaScripts -->
	<script src="js/jquery-2.1.1.min.js"></script>
	<script src="js/tether.min.js"></script>
	<script
		src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.0/js/bootstrap.min.js"></script>

	<div class="container">
		<footer class="footer">
			<br>
			<hr>
			<p>
				<p class="copyright"><a href="http://www.tju.edu.cn//">Tianjin University</a> &copy; 2019.<br /> If you have any comments, corrections or questions
				<a href="contact.html" target="_top">contact us</a>.</p></span>
			</p>
		</footer>
	</div>	
    
    
</body>
</html>

